Initial Commit

diff --git a/templates/blobstore/blobstore_upload_pipeline.v1.yml b/templates/blobstore/blobstore_upload_pipeline.v1.yml
--- a/templates/blobstore/blobstore_upload_pipeline.v1.yml
+++ b/templates/blobstore/blobstore_upload_pipeline.v1.yml
@@ -124,34 +124,40 @@ jobs:
               TILE_FILE_PATH=`find $TILE_DIRECTORY_PATH -name *.pivotal | sort | head -1`
               tile_metadata=$(unzip -l $TILE_FILE_PATH | grep "metadata" | grep "ml$" | awk '{print $NF}' );
               stemcell_version_reqd=$(unzip -p $TILE_FILE_PATH $tile_metadata | grep -A4 stemcell | grep "version:"  | grep -Ei "[0-9]{4,}" | awk '{print $NF}' | sed -e "s/'//g"  );
-              pivnet-cli login --api-token=$PIVNET_API_TOKEN
-              pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd -g "*${IAAS}*" --accept-eula
-              if [ $? != 0 ]; then
-               min_version=$(echo $stemcell_version_reqd | awk -F '.' '{print $2}')
-               if [ "$min_version" == "" ]; then
-                 for min_version in $(seq 0  100)
-                 do
-                    pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd.$min_version -g "*${IAAS}*" --accept-eula && break
-                 done
-               else
-                 echo "Stemcell version $stemcell_version_reqd not found !!, giving up"
-                 exit 1
-               fi
+              if [ "$stemcell_version_reqd" != "" ]; then
+                pivnet-cli login --api-token=$PIVNET_API_TOKEN
+                pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd -g "*${IAAS}*" --accept-eula
+                if [ $? != 0 ]; then
+                 min_version=$(echo $stemcell_version_reqd | awk -F '.' '{print $2}')
+                 if [ "$min_version" == "" ]; then
+                   for min_version in $(seq 0  100)
+                   do
+                      pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd.$min_version -g "*${IAAS}*" --accept-eula && break
+                   done
+                 else
+                   echo "Stemcell version $stemcell_version_reqd not found !!, giving up"
+                   exit 1
+                 fi
+                fi
+
+                SC_FILE_PATH=`find ./ -name bosh*.tgz`;
+                if [ -f "$SC_FILE_PATH" ]; then
+                  echo "Stemcell file found!"
+                else
+                  echo "Stemcell file not found!";
+                  exit 1;
+                fi
               fi
 
-              SC_FILE_PATH=`find ./ -name bosh*.tgz`;
-              if [ -f "$SC_FILE_PATH" ]; then
-                echo "Stemcell file found!"
-              else
-                echo "Stemcell file not found!";
-                exit 1;
+              if [ "$SC_FILE_PATH" != "" ]; then
+                cp $SC_FILE_PATH input-{{ resource['base_type'] }}-{{ resource['name'] }}
               fi
 
-              tar cfz output-tile-stemcell-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz \
-                    ./input-{{ resource['base_type'] }}-{{ resource['name'] }}/*.pivotal $SC_FILE_PATH
-
+              cd input-{{ resource['base_type'] }}-{{ resource['name'] }}
+              tar cfz ../output-tile-stemcell-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz \
+                    *.pivotal bosh*tgz || true
+              cd ..
               mv $TILE_FILE_PATH output-{{ resource['base_type'] }}-{{ resource['name'] }}
-
               ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }}/ output-tile-stemcell-{{ resource['name'] }}/
           path: /bin/bash
       task: prepare-{{ resource['base_type'] }}-{{ resource['name'] }}-bits-to-export
@@ -326,32 +332,39 @@ jobs:
             TILE_FILE_PATH=`find $TILE_DIRECTORY_PATH -name *.pivotal | sort | head -1`
             tile_metadata=$(unzip -l $TILE_FILE_PATH | grep "metadata" | grep "ml$" | awk '{print $NF}' );
             stemcell_version_reqd=$(unzip -p $TILE_FILE_PATH $tile_metadata | grep -A4 stemcell | grep "version:"  | grep -Ei "[0-9]{4,}" | awk '{print $NF}' | sed -e "s/'//g"  );
-            pivnet-cli login --api-token=$PIVNET_API_TOKEN
-            pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd -g "*${IAAS}*" --accept-eula
-            if [ $? != 0 ]; then
-             min_version=$(echo $stemcell_version_reqd | awk -F '.' '{print $2}')
-             if [ "$min_version" == "" ]; then
-               for min_version in $(seq 0  100)
-               do
-                  pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd.$min_version -g "*${IAAS}*" --accept-eula && break
-               done
-             else
-               echo "Stemcell version $stemcell_version_reqd not found !!, giving up"
-               exit 1
-             fi
-            fi
-            SC_FILE_PATH=`find ./ -name bosh*.tgz`;
-            if [ -f "$SC_FILE_PATH" ]; then
-              echo "Stemcell file found!"
-            else
-              echo "Stemcell file not found!";
-              exit 1;
+            if [ "$stemcell_version_reqd" != "" ]; then
+              pivnet-cli login --api-token=$PIVNET_API_TOKEN
+              pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd -g "*${IAAS}*" --accept-eula
+              if [ $? != 0 ]; then
+               min_version=$(echo $stemcell_version_reqd | awk -F '.' '{print $2}')
+               if [ "$min_version" == "" ]; then
+                 for min_version in $(seq 0  100)
+                 do
+                    pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd.$min_version -g "*${IAAS}*" --accept-eula && break
+                 done
+               else
+                 echo "Stemcell version $stemcell_version_reqd not found !!, giving up"
+                 exit 1
+               fi
+              fi
+              SC_FILE_PATH=`find ./ -name bosh*.tgz`;
+              if [ -f "$SC_FILE_PATH" ]; then
+                echo "Stemcell file found!"
+              else
+                echo "Stemcell file not found!";
+                exit 1;
+              fi
             fi
 
-            tar cfz output-tile-stemcell-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz \
-                    ./input-{{ resource['base_type'] }}-{{ resource['name'] }}/*.pivotal $SC_FILE_PATH
+            if [ "$SC_FILE_PATH" != "" ]; then
+              cp $SC_FILE_PATH input-{{ resource['base_type'] }}-{{ resource['name'] }}
+            fi
+
+            cd input-{{ resource['base_type'] }}-{{ resource['name'] }}
+            tar cfz ../output-tile-stemcell-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz \
+                  *.pivotal bosh*tgz || true
+            cd ..
             mv $TILE_FILE_PATH output-{{ resource['base_type'] }}-{{ resource['name'] }}
-
             ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }}/ output-tile-stemcell-{{ resource['name'] }}/
 
         path: /bin/bash
