Finished offline + blobuploader - run1

diff --git a/templates/blobstore/blobstore_upload_pipeline.v1.yml b/templates/blobstore/blobstore_upload_pipeline.v1.yml
--- a/templates/blobstore/blobstore_upload_pipeline.v1.yml
+++ b/templates/blobstore/blobstore_upload_pipeline.v1.yml
@@ -7,9 +7,7 @@ groups:
   {% for resource in resources %}
   - kickoff-{{ resource['name'] }}-upload-to-blobstore
   {% endfor %}
-  # {% for resource_job in process_resource_jobs %}
-  # - {{ resource_job['name'] }}
-  # {% endfor %}
+
 
 resource_types: {{ source_resource_types }}
 
@@ -18,6 +16,7 @@ jobs:
   plan:
   - aggregate:
     {% for resource in final_input_resources %}
+    {% if 'offline-gen-' not in resource['name'] %}
     - get: {{resource['name']}}
     {% if resource['base_type'] == 'tile' %}
       params: {globs: ["*.pivotal"]}
@@ -25,6 +24,7 @@ jobs:
       params: {globs: ["*((iaas))*"]}
     {% elif resource['base_type'] == 'docker' %}
       params: {rootfs: true}
+    {% endif %}
     {% endif %}
     {% endfor %}
 
@@ -63,77 +63,25 @@ jobs:
     {% elif resource['type'] == 'git' %}
     - config:
         image_resource:
-          source: {repository: nsxedgegen/offline-gen-worker}
+          source: {repository: ubuntu}
           type: docker-image
         inputs:
         - {name: input-{{ resource['base_type'] }}-{{ resource['name'] }} }
-        - {name: offline-gen-repo-converter}
         outputs:
         - {name: output-{{ resource['base_type'] }}-{{ resource['name'] }} }
-        - {name: output-git-docker-images-{{ resource['name'] }}}
         platform: linux
         run:
           args:
           - -exc
           - |
-              echo "Searching for docker images within tasks of nsxt-ansible resource"
               cd input-{{ resource['base_type'] }}-{{ resource['name'] }}
-              PIPELINE_REPO_CONVERTER=$(find .. -name "pipeline_task_converter.py")
-              python $PIPELINE_REPO_CONVERTER . "{{resource['task_list']}}" "{{resource['blobstore_source']}}" \
-                 ../output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json
               tar cfz ../output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz .
               cd ..
-              ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }} output-git-docker-images-{{ resource['name'] }}
+              ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }}
           path: /bin/bash
       task: prepare-{{ resource['base_type'] }}-{{ resource['name'] }}-bit-to-export
-    # - config:
-    #     image_resource:
-    #       source: {repository: concourse/docker-image-resource }
-    #       type: docker-image
-    #     inputs:
-    #     - {name: output-git-docker-images-{{ resource['name'] }} }
-    #     outputs:
-    #     - {name: output-docker-{{ resource['name'] }} }
-    #     platform: linux
-    #     run:
-    #       args:
-    #         - -exc
-    #         - |
-    #             echo "Exporting {{ resource['name'] }} git docker images"
-    #             echo '{ "user": "root", "env": [ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "LANG=C", "HOME=/root" ] }' > /tmp/metadata.json
-    #             mkdir export-directory;
-    #             cd export-directory;
-    #             no_of_images=$(cat ../output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json | /usr/bin/jq '.docker_images | length')
-    #             index=0
-    #             while ($index -lt $no_of_images)
-    #             do
-    #               docker_image=$(cat ../output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json  | /usr/bin/jq --argjson index $index '.docker_images\\[$index\\]' )
-    #               repo=$(echo $docker_image | /usr/bin/jq -r .source.repository )
-    #               version=$(echo $docker_image | /usr/bin/jq -r .source.tag )
-    #               if [ "$version" == "" -o "$version" == "null"  ]; then
-    #                 version='latest'
-    #               fi
-    #               docker pull $repo:$version
-    #               docker save $repo:$version > ${repo}-${version}.tar
-    #               mkdir t1
-    #               cd t1
-    #               tar xvf ../${repo}-${version}.tar
-    #               cp /tmp/metadata.json .
-    #               tar cfz ../${repo}-${version}.tgz .
-    #               cd ..
-    #               rm -rf t1 ${repo}-${version}.tar
-    #               mv ${repo}-${version}.tgz ../output-docker-images-{{ resource['name'] }}/
-    #               index=$(expr index + 1)
-    #             done
-    #             cd ..
-    #             ls -l output-docker-images-{{ resource['name'] }}/
-    #             cd output-docker-images-{{ resource['name'] }}/
-    #             tar cvf {{ resource['name'] }}-docker-tarball.tar .
-    #       path: /bin/bash
-    #   task: save-{{ resource['name'] }}-git-docker-images
-    #   privileged: true # Needed for running docker within docker
 
-    {% elif resource['type'] == 'pivnet_non_tile' %}
+    {% elif resource['base_type'] == 'pivnet-non-tile' %}
     - config:
         image_resource:
           source: {repository: czero/cflinuxfs2}
@@ -156,14 +104,13 @@ jobs:
               ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }}/
           path: /bin/bash
       task: prepare-{{ resource['name'] }}-{{ resource['base_type'] }}-bit-to-export
-    {% elif resource['type'] == 'tile' %}
+    {% elif resource['base_type'] == 'tile' %}
     - config:
         image_resource:
           source: {repository: czero/cflinuxfs2}
           type: docker-image
         inputs:
         - {name: input-{{ resource['base_type'] }}-{{ resource['name'] }} }
-        - {name: offline-gen-stemcell-downloader}
         outputs:
         - {name: output-{{ resource['base_type'] }}-{{ resource['name'] }} }
         - {name: output-stemcell-{{ resource['name'] }} }
@@ -174,9 +121,25 @@ jobs:
           - -exc
           - |
               echo "Copying {{ resource['name'] }} tile bits"
-              OFFLINE_STEMCELL_DOWNLOADER=$(find . -name find_and_download_stemcell.sh)
-              chmod +x $OFFLINE_STEMCELL_DOWNLOADER
-              $OFFLINE_STEMCELL_DOWNLOADER ./input-{{ resource['base_type'] }}-{{ resource['name'] }}
+              TILE_DIRECTORY_PATH=./input-{{ resource['base_type'] }}-{{ resource['name'] }}
+              TILE_FILE_PATH=`find $TILE_DIRECTORY_PATH -name *.pivotal | sort | head -1`
+              tile_metadata=$(unzip -l $TILE_FILE_PATH | grep "metadata" | grep "ml$" | awk '{print $NF}' );
+              stemcell_version_reqd=$(unzip -p $TILE_FILE_PATH $tile_metadata | grep -A4 stemcell | grep "version:"  | grep -Ei "[0-9]{4,}" | awk '{print $NF}' | sed -e "s/'//g"  );
+              pivnet-cli login --api-token=$PIVNET_API_TOKEN
+              pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd -g "*${IAAS}*" --accept-eula
+              if [ $? != 0 ]; then
+               min_version=$(echo $stemcell_version_reqd | awk -F '.' '{print $2}')
+               if [ "$min_version" == "" ]; then
+                 for min_version in $(seq 0  100)
+                 do
+                    pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd.$min_version -g "*${IAAS}*" --accept-eula && break
+                 done
+               else
+                 echo "Stemcell version $stemcell_version_reqd not found !!, giving up"
+                 exit 1
+               fi
+              fi
+
               SC_FILE_PATH=`find ./ -name bosh*.tgz`;
               if [ -f "$SC_FILE_PATH" ]; then
                 echo "Stemcell file found!"
@@ -231,21 +194,19 @@ jobs:
       {% if resource['base_type'] == 'docker' %}
       params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-docker*.tgz }
 
-      {% elif resource['type'] == 'git' %}
+      {% elif resource['base_type'] == 'git' %}
 
       params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz }
-    - put: output-git-docker-images-{{ resource['name'] }}
-      params: { file: output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json }
 
-    - put: output-docker-images-{{ resource['name'] }}
-      params: { file: output-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-tarball.tar }
+    # - put: output-docker-images-{{ resource['name'] }}
+    #   params: { file: output-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-tarball.tar }
 
-      {% elif resource['type'] == 'tile' %}
+      {% elif resource['base_type'] == 'tile' %}
       params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/*.pivotal }
     - put: output-stemcell-{{ resource['name'] }}
       params: { file: output-stemcell-{{ resource['name'] }}/bosh-*.tgz }
 
-      {% elif resource['type'] == 'pivnet_non_tile' %}
+      {% elif resource['base_type'] == 'pivnet-non-tile' %}
       params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-{{ resource['base_type'] }}-* }
 
       {% else %}
@@ -270,7 +231,6 @@ jobs:
     params: {rootfs: true}
   {% elif resource['base_type'] == 'git' %}
     params: {rootfs: true}
-  - get: offline-gen-repo-converter
   {% endif %}
   {% if resource['base_type'] == 'docker' %}
   - config:
@@ -301,81 +261,28 @@ jobs:
               ls -l ../output-{{ resource['base_type'] }}-{{ resource['name'] }}/;
         path: /bin/bash
     task: prepare-{{ resource['name'] }}-docker-image-to-export
-  {% elif resource['type'] == 'git' %}
+  {% elif resource['base_type'] == 'git' %}
   - config:
       image_resource:
-        source: {repository: nsxedgegen/offline-gen-worker}
+        source: {repository: ubuntu}
         type: docker-image
       inputs:
       - {name: input-{{ resource['base_type'] }}-{{ resource['name'] }} }
-      - {name: offline-gen-repo-converter}
       outputs:
       - {name: output-{{ resource['base_type'] }}-{{ resource['name'] }} }
-      - {name: output-git-docker-images-{{ resource['name'] }}}
       platform: linux
       run:
         args:
         - -exc
         - |
-            echo "Searching for docker images within tasks of nsxt-ansible resource"
             cd input-{{ resource['base_type'] }}-{{ resource['name'] }}
-            PIPELINE_REPO_CONVERTER=$(find .. -name "pipeline_task_converter.py")
-            python $PIPELINE_REPO_CONVERTER . "{{resource['task_list']}}" "{{resource['blobstore_source']}}" \
-               ../output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json
             tar cfz ../output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz .
             cd ..
-            ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }} output-git-docker-images-{{ resource['name'] }}
+            ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }}
         path: /bin/bash
     task: prepare-{{ resource['base_type'] }}-{{ resource['name'] }}-bit-to-export
-  #
-  # - config:
-  #     image_resource:
-  #       source: {repository: concourse/docker-image-resource }
-  #       type: docker-image
-  #     inputs:
-  #     - {name: output-git-docker-images-{{ resource['name'] }} }
-  #     outputs:
-  #     - {name: output-docker-{{ resource['name'] }} }
-  #     platform: linux
-  #     run:
-  #       args:
-  #         - -exc
-  #         - |
-  #             echo "Exporting {{ resource['name'] }} git docker images"
-  #             echo '{ "user": "root", "env": [ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "LANG=C", "HOME=/root" ] }' > /tmp/metadata.json
-  #             mkdir export-directory;
-  #             cd export-directory;
-  #             no_of_images=$(cat ../output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json | /usr/bin/jq '.docker_images | length')
-  #             index=0
-  #             while [ $index -lt $no_of_images ]
-  #             do
-  #               docker_image=$(cat ../output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json | /usr/bin/jq --argjson index $index '.docker_images[$index]' )
-  #               repo=$(echo $docker_image | /usr/bin/jq '.source.repository' )
-  #               version=$(echo $docker_image | /usr/bin/jq .source.tag )
-  #               if [ "$version" == "" -o "$version" == "null" ]; then
-  #                 version=latest
-  #               fi
-  #               docker pull ${repo}:${version}
-  #               docker save ${repo}:${version} > ${repo}-${version}.tar
-  #               mkdir t1
-  #               cd t1
-  #               tar xvf ../${repo}-${version}.tar
-  #               cp /tmp/metadata.json .
-  #               tar cfz ../${repo}-${version}.tgz .
-  #               cd ..
-  #               rm -rf t1 ${repo}-${version}.tar
-  #               mv ${repo}-${version}.tgz ../output-docker-images-{{ resource['name'] }}/
-  #               index=$(expr index + 1)
-  #             done
-  #             cd ..
-  #             ls -l output-docker-images-{{ resource['name'] }}/
-  #             cd output-docker-images-{{ resource['name'] }}/
-  #             tar cvf {{ resource['name'] }}-docker-tarball.tar .
-  #       path: /bin/bash
-  #   task: save-{{ resource['name'] }}-git-docker-images
-  #   privileged: true # Needed for running docker within docker
 
-  {% elif resource['type'] == 'pivnet_non_tile' %}
+  {% elif resource['base_type'] == 'pivnet-non-tile' %}
   - config:
       image_resource:
         source: {repository: czero/cflinuxfs2}
@@ -398,14 +305,13 @@ jobs:
             ls -l output-{{ resource['base_type'] }}-{{ resource['name'] }}/
         path: /bin/bash
     task: prepare-{{ resource['name'] }}-{{ resource['base_type'] }}-bit-to-export
-  {% elif resource['type'] == 'tile' %}
+  {% elif resource['base_type'] == 'tile' %}
   - config:
       image_resource:
         source: {repository: czero/cflinuxfs2}
         type: docker-image
       inputs:
       - {name: input-{{ resource['base_type'] }}-{{ resource['name'] }} }
-      - {name: offline-gen-stemcell-downloader}
       outputs:
       - {name: output-{{ resource['base_type'] }}-{{ resource['name'] }} }
       - {name: output-stemcell-{{ resource['name'] }} }
@@ -416,9 +322,24 @@ jobs:
         - -exc
         - |
             echo "Copying {{ resource['name'] }} tile bits"
-            OFFLINE_STEMCELL_DOWNLOADER=$(find . -name find_and_download_stemcell.sh)
-            chmod +x $OFFLINE_STEMCELL_DOWNLOADER
-            $OFFLINE_STEMCELL_DOWNLOADER ./input-{{ resource['base_type'] }}-{{ resource['name'] }}
+            TILE_DIRECTORY_PATH=./input-{{ resource['base_type'] }}-{{ resource['name'] }}
+            TILE_FILE_PATH=`find $TILE_DIRECTORY_PATH -name *.pivotal | sort | head -1`
+            tile_metadata=$(unzip -l $TILE_FILE_PATH | grep "metadata" | grep "ml$" | awk '{print $NF}' );
+            stemcell_version_reqd=$(unzip -p $TILE_FILE_PATH $tile_metadata | grep -A4 stemcell | grep "version:"  | grep -Ei "[0-9]{4,}" | awk '{print $NF}' | sed -e "s/'//g"  );
+            pivnet-cli login --api-token=$PIVNET_API_TOKEN
+            pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd -g "*${IAAS}*" --accept-eula
+            if [ $? != 0 ]; then
+             min_version=$(echo $stemcell_version_reqd | awk -F '.' '{print $2}')
+             if [ "$min_version" == "" ]; then
+               for min_version in $(seq 0  100)
+               do
+                  pivnet-cli download-product-files -p "stemcells" -r $stemcell_version_reqd.$min_version -g "*${IAAS}*" --accept-eula && break
+               done
+             else
+               echo "Stemcell version $stemcell_version_reqd not found !!, giving up"
+               exit 1
+             fi
+            fi
             SC_FILE_PATH=`find ./ -name bosh*.tgz`;
             if [ -f "$SC_FILE_PATH" ]; then
               echo "Stemcell file found!"
@@ -465,17 +386,13 @@ jobs:
     params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-*.tgz }
 
     {% elif resource['type'] == 'git' %}
-
     params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-tarball.tgz }
-  - put: output-git-docker-images-{{ resource['name'] }}
-    params: { file: output-git-docker-images-{{ resource['name'] }}/{{ resource['name'] }}-docker-images.json }
-
     {% elif resource['type'] == 'tile' %}
     params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/*.pivotal }
   - put: output-stemcell-{{ resource['name'] }}
     params: { file: output-stemcell-{{ resource['name'] }}/bosh-*.tgz }
 
-    {% elif resource['type'] == 'pivnet_non_tile' %}
+    {% elif resource['base_type'] == 'pivnet-non-tile' %}
     params: { file: output-{{ resource['base_type'] }}-{{ resource['name'] }}/{{ resource['name'] }}-{{ resource['base_type'] }}-* }
 
     {% else %}
@@ -487,17 +404,19 @@ jobs:
 
 resources:
   {% for resource in final_input_resources %}
+  {% if 'offline-gen-' not in resource['name'] %}
 - name: {{ resource['name'] }}
   source: {{ resource['source'] }}
   type: {{ resource['type'] }}
+  {% endif %}
   {% endfor %}
   {% for resource in final_output_resources %}
 - name: {{ resource['name'] }}
   source:
-    access_key_id: ((minio_access_id))
-    bucket: ((minio_bucket))
-    endpoint: ((minio_endpoint))
-    secret_access_key: ((minio_access_key))
+    access_key_id: ((s3_access_key_id))
+    bucket: ((s3_bucket))
+    endpoint: ((s3_endpoint))
+    secret_access_key: ((s3_secret_access_key))
     regexp: {{ resource['regexp'] }}
   type: s3
   {% endfor %}
